//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestJoseGonzalez.ConsultaGeneralServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratCancionesGeneral", Namespace="Wcf.TestPrueba.DistributedServices.Services")]
    [System.SerializableAttribute()]
    public partial class ContratCancionesGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string musicaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string musica {
            get {
                return this.musicaField;
            }
            set {
                if ((object.ReferenceEquals(this.musicaField, value) != true)) {
                    this.musicaField = value;
                    this.RaisePropertyChanged("musica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractSonidosGeneral", Namespace="Wcf.TestPrueba.DistributedServices.Services")]
    [System.SerializableAttribute()]
    public partial class ContractSonidosGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TestJoseGonzalez.ConsultaGeneralServices.EntidadesGrillo[] _GrilloField;
        
        private TestJoseGonzalez.ConsultaGeneralServices.EntidadesLibelula[] _LibelulaField;
        
        private TestJoseGonzalez.ConsultaGeneralServices.EntidadesRana[] _RanaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestJoseGonzalez.ConsultaGeneralServices.EntidadesGrillo[] _Grillo {
            get {
                return this._GrilloField;
            }
            set {
                if ((object.ReferenceEquals(this._GrilloField, value) != true)) {
                    this._GrilloField = value;
                    this.RaisePropertyChanged("_Grillo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestJoseGonzalez.ConsultaGeneralServices.EntidadesLibelula[] _Libelula {
            get {
                return this._LibelulaField;
            }
            set {
                if ((object.ReferenceEquals(this._LibelulaField, value) != true)) {
                    this._LibelulaField = value;
                    this.RaisePropertyChanged("_Libelula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TestJoseGonzalez.ConsultaGeneralServices.EntidadesRana[] _Rana {
            get {
                return this._RanaField;
            }
            set {
                if ((object.ReferenceEquals(this._RanaField, value) != true)) {
                    this._RanaField = value;
                    this.RaisePropertyChanged("_Rana");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadesGrillo", Namespace="http://schemas.datacontract.org/2004/07/Wcf.TestPrueba.DistributedServices.Contra" +
        "ct.Entidades")]
    [System.SerializableAttribute()]
    public partial class EntidadesGrillo : TestJoseGonzalez.ConsultaGeneralServices.Animal {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadesLibelula", Namespace="http://schemas.datacontract.org/2004/07/Wcf.TestPrueba.DistributedServices.Contra" +
        "ct.Entidades")]
    [System.SerializableAttribute()]
    public partial class EntidadesLibelula : TestJoseGonzalez.ConsultaGeneralServices.Animal {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadesRana", Namespace="http://schemas.datacontract.org/2004/07/Wcf.TestPrueba.DistributedServices.Contra" +
        "ct.Entidades")]
    [System.SerializableAttribute()]
    public partial class EntidadesRana : TestJoseGonzalez.ConsultaGeneralServices.Animal {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://schemas.datacontract.org/2004/07/Wcf.TestPrueba.DistributedServices.Contra" +
        "ct.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestJoseGonzalez.ConsultaGeneralServices.EntidadesLibelula))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestJoseGonzalez.ConsultaGeneralServices.EntidadesRana))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestJoseGonzalez.ConsultaGeneralServices.EntidadesGrillo))]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAnimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAnimal {
            get {
                return this.NombreAnimalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAnimalField, value) != true)) {
                    this.NombreAnimalField = value;
                    this.RaisePropertyChanged("NombreAnimal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sonido {
            get {
                return this.SonidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SonidoField, value) != true)) {
                    this.SonidoField = value;
                    this.RaisePropertyChanged("Sonido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsultaGeneralServices.IConsultarCansiones")]
    public interface IConsultarCansiones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultarCansiones/GetDataCanciones", ReplyAction="http://tempuri.org/IConsultarCansiones/GetDataCancionesResponse")]
        TestJoseGonzalez.ConsultaGeneralServices.ContratCancionesGeneral[] GetDataCanciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultarCansiones/GetDataCanciones", ReplyAction="http://tempuri.org/IConsultarCansiones/GetDataCancionesResponse")]
        System.Threading.Tasks.Task<TestJoseGonzalez.ConsultaGeneralServices.ContratCancionesGeneral[]> GetDataCancionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultarCansiones/GetDataSonidos", ReplyAction="http://tempuri.org/IConsultarCansiones/GetDataSonidosResponse")]
        TestJoseGonzalez.ConsultaGeneralServices.ContractSonidosGeneral[] GetDataSonidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsultarCansiones/GetDataSonidos", ReplyAction="http://tempuri.org/IConsultarCansiones/GetDataSonidosResponse")]
        System.Threading.Tasks.Task<TestJoseGonzalez.ConsultaGeneralServices.ContractSonidosGeneral[]> GetDataSonidosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsultarCansionesChannel : TestJoseGonzalez.ConsultaGeneralServices.IConsultarCansiones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarCansionesClient : System.ServiceModel.ClientBase<TestJoseGonzalez.ConsultaGeneralServices.IConsultarCansiones>, TestJoseGonzalez.ConsultaGeneralServices.IConsultarCansiones {
        
        public ConsultarCansionesClient() {
        }
        
        public ConsultarCansionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarCansionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarCansionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarCansionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestJoseGonzalez.ConsultaGeneralServices.ContratCancionesGeneral[] GetDataCanciones() {
            return base.Channel.GetDataCanciones();
        }
        
        public System.Threading.Tasks.Task<TestJoseGonzalez.ConsultaGeneralServices.ContratCancionesGeneral[]> GetDataCancionesAsync() {
            return base.Channel.GetDataCancionesAsync();
        }
        
        public TestJoseGonzalez.ConsultaGeneralServices.ContractSonidosGeneral[] GetDataSonidos() {
            return base.Channel.GetDataSonidos();
        }
        
        public System.Threading.Tasks.Task<TestJoseGonzalez.ConsultaGeneralServices.ContractSonidosGeneral[]> GetDataSonidosAsync() {
            return base.Channel.GetDataSonidosAsync();
        }
    }
}
